# IONOS Deploy Now Configuration
version: 1.0

bootstrap:
  # Configuración del build
  - name: Install dependencies
    command: npm ci
  - name: Build project
    command: npm run build

# Configuración de hosting
hosting:
  # Carpeta que se despliega
  dist-folder: dist
  
  # Página de error 404
  error-document: 404.html
  
  # Headers de seguridad y cache
  headers:
    - pattern: "**/*.{js,css,svg,jpg,jpeg,png,gif,webp,woff,woff2}"
      headers:
        - key: Cache-Control
          value: public, max-age=31536000, immutable
    - pattern: "**/*.html"
      headers:
        - key: Cache-Control
          value: public, max-age=0, must-revalidate
  
  # Redirecciones para SPA/404
  redirects:
    - source: "**"
      destination: /404.html
      type: 404

